config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :poodles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  has_rich_text :content
end

app/models/poodle.rb
class Poodle < ApplicationRecord
  # connected to both the animals_primary db for writing and the animals_replica for reading
  connects_to database: { writing: :primary, reading: :animals_replica }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/poodles_controller.rb
require_dependency 'cute_name'

class PoodlesController < ApplicationController
  before_action :set_poodle, only: [:show, :edit, :update, :destroy]

  # GET /poodles
  # GET /poodles.json
  def index
    @poodles = Poodle.all
  end

  # GET /poodles/1
  # GET /poodles/1.json
  def show
    Poodle.connected_to(role: :writing) do
      @poodle = Poodle.find(params[:id])
    end
  end

  # GET /poodles/new
  def new
    @poodle = Poodle.new(name: CuteName.generate)
  end

  # GET /poodles/1/edit
  def edit
  end

  # POST /poodles
  # POST /poodles.json
  def create
    @poodle = Poodle.new(poodle_params)

    respond_to do |format|
      saved = false
      Poodle.connected_to(role: :writing) do
        saved = @poodle.save
      end

      if saved
        format.html { redirect_to @poodle, notice: 'Poodle was successfully created.' }
        format.json { render :show, status: :created, location: @poodle }
      else
        format.html { render :new }
        format.json { render json: @poodle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poodles/1
  # PATCH/PUT /poodles/1.json
  def update
    respond_to do |format|
      if @poodle.update(poodle_params)
        format.html { redirect_to @poodle, notice: 'Poodle was successfully updated.' }
        format.json { render :show, status: :ok, location: @poodle }
      else
        format.html { render :edit }
        format.json { render json: @poodle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poodles/1
  # DELETE /poodles/1.json
  def destroy
    @poodle.destroy
    respond_to do |format|
      format.html { redirect_to poodles_url, notice: 'Poodle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poodle
      @poodle = Poodle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poodle_params
      params.require(:poodle).permit(:name, :weight, :height, :avatar, :birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/poodles_helper.rb
module PoodlesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesomerails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/poodles/_form.html.erb
<%= form_with(model: poodle, local: true) do |form| %>
  <% if poodle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poodle.errors.count, "error") %> prohibited this poodle from being saved:</h2>

      <ul>
      <% poodle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :birth %>
    <%= form.datetime_select :birth %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/poodles/edit.html.erb
<h1>Editing Poodle</h1>

<%= render 'form', poodle: @poodle %>

<%= link_to 'Show', @poodle %> |
<%= link_to 'Back', poodles_path %>

app/views/poodles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poodles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Avatar</th>
      <th>Birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poodles.each do |poodle| %>
      <tr>
        <td><%= poodle.name %></td>
        <td><%= poodle.weight %></td>
        <td><%= poodle.height %></td>
        <td><%= poodle.avatar %></td>
        <td><%= poodle.birth %></td>
        <td><%= link_to 'Show', poodle %></td>
        <td><%= link_to 'Edit', edit_poodle_path(poodle) %></td>
        <td><%= link_to 'Destroy', poodle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poodle', new_poodle_path %>

app/views/poodles/new.html.erb
<h1>New Poodle</h1>

<%= render 'form', poodle: @poodle %>

<%= link_to 'Back', poodles_path %>

app/views/poodles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poodle.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @poodle.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @poodle.height %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @poodle.avatar %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @poodle.birth %>
</p>

<%= link_to 'Edit', edit_poodle_path(@poodle) %> |
<%= link_to 'Back', poodles_path %>